services: 
  database:
    image: postgres:14 
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: 
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - backend
  backend:
    image: recap
    build: ./recap 
    env_file: 
      - ./.env
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - backend
      - backendAPI
networks:
  backend:
    internal: true
  backendAPI:
    external: true
volumes:
  db_data:
